//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int Id { get; set; }
        public System.DateTime DateIn { get; set; }
        public System.DateTime DateOut { get; set; }
        public int RoomId { get; set; }
        public int RateId { get; set; }
        public int QuantityPeople { get; set; }
    
        public virtual Rates Rates { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
